//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamilSafiullin320_EducationalPractice.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Id_application { get; set; }
        public int Id_discipline { get; set; }
        public string Id_speciality { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Speciality Speciality { get; set; }
    }
}
