//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamilSafiullin320_EducationalPractice.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country_SKamil
    {
        public int Id_country { get; set; }
        public string Continent { get; set; }
        public string Name { get; set; }
        public Nullable<int> Square { get; set; }
    }
}
