//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamilSafiullin320_EducationalPractice.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department_head
    {
        public int Id_department_head { get; set; }
        public Nullable<int> Experience { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
