//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamilSafiullin320_EducationalPractice.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Exam = new HashSet<Exam>();
        }
    
        public int Id_employee { get; set; }
        public string Cipher { get; set; }
        public string Surname { get; set; }
        public string Post { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public int Id_chief { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Department_head Department_head { get; set; }
        public virtual Engineer Engineer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam> Exam { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
