//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamilSafiullin320_EducationalPractice.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int Id_exam { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Id_discipline { get; set; }
        public int Id_student { get; set; }
        public int Id_employee { get; set; }
        public string Audience { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
