//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamilSafiullin320_EducationalPractice.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Educational_practice_320_KamilEntities : DbContext
    {
        public Educational_practice_320_KamilEntities()
            : base("name=Educational_practice_320_KamilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academician> Academician { get; set; }
        public virtual DbSet<Animal_SKamil> Animal_SKamil { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Control_SKamil> Control_SKamil { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Country_SKamil> Country_SKamil { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Department_head> Department_head { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Engineer> Engineer { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Flower_SKamil> Flower_SKamil { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Ученики> Ученики { get; set; }
        public virtual DbSet<Гимназисты> Гимназисты { get; set; }
    }
}
